# This is a sample SlipwayDefaultPipeline, This example contains all of the configurable parameters and hints on how to use them.
apiVersion: spinnaker.cloud.transportation.trimble.com/v1alpha1
kind: SlipwayDefaultPipeline
metadata:
  # This is the name of the K8S crd, this name is also used to generate the name of the spinnaker application that is created.
  name: tcx-entitlementsnavbarpermissions # unique key (enforced by Spinnaker application)
  namespace: ttc-spinnaker-operator
spec:
  # Team and Contacts populate the relevant banners and fields in spinnaker with the contact information.
  team: tcx-kuebix
  contacts:
    productOwners:
    - gokulnath_raghavan@trimble.com
    technicalContacts:
    - thirumaniraj_rr@trimble.com
    - mothi_sampath@trimble.com
  description: |-
    Describe your service here. This description will be accessible in the Spinnaker application object.
  # If a spinnaker application is manged, the spinnaker operator will lock the pipelines it creates so they cannot be updated within the spinnaker UI and keep them in sync with this YAML file.
  # If this is set to false, the operator will only create pipelines and applications that do not exist. It will not update existing pipelines and will not lock them.
  # Set managed to false if you want to be able to make changes in the spinnaker UI to your pipelines after they are generated
  managed: true
  # This controls where deployment notifications are sent, this must be a valid chat webhook.
  googleChatWebhookUrl: https://chat.googleapis.com/v1/spaces/AAAAwwQc5Ts/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=gZUqNs3olUnvuTfWFmVplWgEW_LSji8o8WIsRPeYcus%3D
  # The spinnaker operator must have the roles defined here in order to create the pipelines.
  rbac:
    enabled: true
    applicationPermissions:
      read:
        - tcx-kuebix
        - tcx
      write:
        - tcx-kuebix
      execute:
        - tcx-kuebix
    releasePipelineRoles:
      - tcx-kuebix
      - tcx-lower
      - tcx-prod
      - tcx-docker-registry
   # Enabling deployCrd will create a pipeline in this application that deploys this CRD onto the cluster hosting the spinnaker operator. 
  deployCrd:
    # When set to false this will delete the deploy crd pipeline if it exists
    enabled: true
    # The location of this CRD. It is recommended this be located within the application repository. 
    kubernetesManifest:
      bitbucketFqdn: https://bitbucket.trimble.tools/rest/api/1.0      
      bitbucketProject: TCX-PRODUCT                         
      bitbucketRepo: trimble.transportation.entitlements.navbar.permissions 
      bitbucketSpinnakerAccount: bitbucket-tcx-ci
      manifestPath: spinnaker.yaml
      bitbucketBranch: main
    # The cluster running the ttc-spinnaker-operator. If RBAC is enabled the pipelineRoles key must have a role that can deploy to this cluster. 
    cluster: gke_slipway-prod_us-central1_slipway-tools-gke-central1-04
    # This is the namespace the operator is running in. Will override namespace in the manifest. 
    namespace: ttc-spinnaker-operator
    # The role that can deploy to the cluster above 
    pipelineRoles: 
      - tcx-kuebix
      - slipway-admin
  artifacts:
    containerArtifact:
      imageRegistrySpinnakerAccount: docker-registry
      imageRegistrySpinnakerTriggerAccount: tcx-docker-registry
      imageRegistry: tcxcontainers.azurecr.io
      imageRegistryOrganization: tcx
      imageName: entitlementsnavbarpermissions
      imageTagTriggerRegEx: '^[\d\.]+-\w+$'
    kubernetesManifest:
      bitbucketFqdn: https://bitbucket.trimble.tools/rest/api/1.0
      bitbucketProject: TCX-PRODUCT
      bitbucketRepo: trimble.transportation.entitlements.navbar.permissions
      bitbucketSpinnakerAccount: bitbucket-tcx-ci
      manifestPath: k8s.yaml
  # Define any jenkins stages that are required. This is flexible and stages can be added or removed as needed.
  jenkinsStages:
    # The key is used as the ID of the stage when binding to environments
    imageValidator:
      # Name is the display name of the stage
      name: Image Validator
      # The jenkins server where this job runs, must exist in spinnaker
      controller: jenkinsV2
      # The Job Name
      job: ImageValidator
      # Any parameters to pass to the job
      parameters:
        DOCKER_IMAGE: ^{#triggerResolvedArtifactByType("docker/image")["reference"]}
    sonarValidator:
      name: Sonar Validator
      controller: jenkinsV2
      job: SonarValidator
      parameters:
        DOCKER_IMAGE: ^{#triggerResolvedArtifactByType("docker/image")["reference"]}
    whitesourceValidator:
      name: Whitesource Validator
      controller: jenkinsV2
      job: WhitesourceValidator
      parameters:
        DOCKER_IMAGE: ^{#triggerResolvedArtifactByType("docker/image")["reference"]}
  # Define any jobs that will be used. These jobs can be attached to environments pre or post deployment.
  jobs:
    # The key is used as the ID of the stage when binding to environments
    smokeTesting:
      # Name is the display name of the stage
      name: Smoke Testing
      # Timeout in minutes for the job
      timeout: 20
      # Fail the pipeline if this job fails, if this is set to false the deployment will continue on failure
      failPipeline: false
      # The manifest for this job. Note this currently does not setup any triggers. It is recommended that this job be in the same repository as the main service.
      kubernetesManifest:
        bitbucketFqdn: https://bitbucket.trimble.tools/rest/api/1.0
        bitbucketProject: TCX-PRODUCT
        bitbucketRepo: trimble.transportation.entitlements.navbar.permissions
        bitbucketSpinnakerAccount: bitbucket-tcx-ci
        # For paths do not add a leading slash. Example: path/to/file/k8s.yaml
        manifestPath: smoke-test/k8s.yaml
    performanceTesting:
      name: Performance Testing
      timeout: 20
      kubernetesManifest:
        bitbucketFqdn: https://bitbucket.trimble.tools/rest/api/1.0
        bitbucketProject: TCX-PRODUCT
        bitbucketRepo: trimble.transportation.entitlements.navbar.permissions
        bitbucketSpinnakerAccount: bitbucket-tcx-ci
        manifestPath: performance-test/k8s.yaml
  # Define as many environments as needed. Each environment will create a separate spinnaker pipeline
  environments:
    # The key for an environment object acts as its name.
    dev:
      # Define the clusters that belong to this environment. These clusters must exist in spinnaker.
      clusters:
        - tcx-lower-east2
      # Any numbers must be quoted
      parameters:
        namespace: dev
        minReplicas: "2"
        maxReplicas: "3"
        loglevel: info
        keyvault: tcx-dev-7c1efc0feee8
        keyvaultResourceGroup: tcx-kuebix
        keyvaultSubscriptionId: c3858f8e-ebe6-4079-a815-8f4d7826f5de
        keyvaultTenantId: 23235593-4c46-41c1-944b-32a03aab96e6
        hosts: entitlementsnavbarpermissions.dev.trimble-transportation.com
        apiGatewayHost: api.dev.slipway.transportation.trimble.com
        deploymentProgressDeadlineSeconds: "600"
        docsHosts: api-docs.dev.trimble-transportation.com
      # Restrict the time this environment can be deployed to.
      restrictedExecutionTimeWindow:
        enabled: false
        startHour: 8
        endHour: 17
      # Jobs that run before this environment deploys. Note: jobs will run in all clusters defined for this environment
      preJobs: []
#      preJobs:
#        - smokeTesting
      # Jobs that run after this environment deploys. Note: jobs will run in all clusters defined for this environment
      postJobs: []
#      postJobs:
#        - smokeTesting
#        - performanceTesting
      # Define if an approval stage will be added before this environment can be deployed.
      requireApproval: false
      # A list of jenkins stages this environment depends on before it can run.
      requiredJenkinsStages: []
      # A list of environments that this environment depends on.
      requiredEnvironments: []
    staging:
      clusters:
        - tcx-staging-east2
        - tcx-staging-west2
      parameters:
        namespace: staging
        minReplicas: "2"
        maxReplicas: "5"
        loglevel: info
        keyvault: tcx-staging-7c1efc0feee8
        keyvaultResourceGroup: tcx-kuebix
        keyvaultSubscriptionId: c3858f8e-ebe6-4079-a815-8f4d7826f5de
        keyvaultTenantId: 23235593-4c46-41c1-944b-32a03aab96e6
        hosts: entitlementsnavbarpermissions.stg.trimble-transportation.com
        apiGatewayHost: api.stg.slipway.transportation.trimble.com
        deploymentProgressDeadlineSeconds: "600"
        docsHosts: api-docs.stg.trimble-transportation.com
      restrictedExecutionTimeWindow:
        enabled: true
        startHour: 8
        endHour: 17
      # Jobs that run before this environment deploys. Note: jobs will run in all clusters defined for this environment
      preJobs: []
#      preJobs:
#        - smokeTesting
      # Jobs that run after this environment deploys. Note: jobs will run in all clusters defined for this environment
      postJobs: []
#      postJobs:
#        - smokeTesting
#        - performanceTesting
      requiredJenkinsStages:
        - imageValidator
        - sonarValidator
        - whitesourceValidator
      requireApproval: true
      requiredEnvironments:
        - dev
    prod:
      clusters:
        - tcx-prod-east2
        - tcx-prod-west2
      parameters:
        namespace: prod
        minReplicas: "2"
        maxReplicas: "5"
        loglevel: info
        keyvault: tcx-prod-7c1efc0feee8
        keyvaultResourceGroup: tcx-kuebix
        keyvaultSubscriptionId: 85cae6cd-7015-422a-ae14-d60a136b559b
        keyvaultTenantId: 23235593-4c46-41c1-944b-32a03aab96e6
        hosts: entitlementsnavbarpermissions.trimble-transportation.com
        apiGatewayHost: api.slipway.transportation.trimble.com
        deploymentProgressDeadlineSeconds: "600"
        docsHosts: api-docs.trimble-transportation.com
      # Jobs that run before this environment deploys. Note: jobs will run in all clusters defined for this environment
      preJobs: []
#      preJobs:
#        - smokeTesting
      # Jobs that run after this environment deploys. Note: jobs will run in all clusters defined for this environment
      postJobs: []
#      postJobs:
#        - smokeTesting
#        - performanceTesting
      requiredJenkinsStages:
        - imageValidator
        - sonarValidator
        - whitesourceValidator
      requireApproval: true
      requiredEnvironments: 
        - staging
