spring:
  application:
    name: navbar-permissions-service
    version: @version@
  profiles:
    active: local
  data:
    mongodb:
      dbname: NavbarPermissionsDB
      database: NavbarPermissionsDB
      uuid-representation: standard

external:
  accountServiceUrl: '#{"${IS_CONTAINER:false}".equals("true") ? "http://tcx-accountappservice" : "https://cloud.dev.api.trimblecloud.com/transportation"}'
  accountServiceEndpoint: /api/core/v2/accounts/
  userServiceUrl: '#{"${IS_CONTAINER:false}".equals("true") ? "http://tcx-iamuserapp" : "https://cloud.dev.api.trimblecloud.com/transportation"}'
  userServiceEndpoint : /iam/v2/users/
  permissionServiceUrl: '#{"${IS_CONTAINER:false}".equals("true") ? "http://tcx-permissionservice" : "https://cloud.dev.api.trimblecloud.com/transportation"}'
  permissionServiceEndpoint : '#{"${IS_CONTAINER:false}".equals("true") ? "/api/v1/role/permissions/" : "/api/v1/manage/roles/permissions/"}'
  authorization:

permissionValuesDb:
  permissionValues:
    -  
     id: network_partners
     permissionValues: 
       - CRM_NetworkPartners
       - CRM_NetworkPartnersV2
       - CRM_NetworkPartnersV3
    -
     id: user_management
     permissionValues:
       - crm-v2-users
    -
     id: planning
     permissionValues:
       - Load Planning Domain
    -
     id: quote_details
     permissionValues:
       - QuoteService
    -
     id: shipment_detail
     permissionValues:
       - Load Planning Domain
    -
     id: order_details
     permissionValues:
       - Load Planning Domain       
    -
     id: accessorial_management
     permissionValues:
       - Accessorial
    -
     id: calendar
     permissionValues:
       - Load Planning Calendar
    -
     id: orphan_invoices
     permissionValues:                               
       - Financials App Service
    -
     id: all_transactions
     permissionValues:                               
       - Financials App Service
    -
     id: matching_rules
     permissionValues:                               
       - Financials App Service
    -
     id: audit_tolerance
     permissionValues:                               
       - Financials App Service
    -
     id: reporting
     permissionValues:                               
       - ReportingAPI
    -
     id: carrier-procurement
     permissionValues:                               
       - Operations Tender Service
    -
     id: carrier-tracking
     permissionValues:                               
       - Trailer-Tracking
    -
     id: equipment
     permissionValues:                               
       - Equipment-Types-Application-Service
    -
     id: handling_units_packages
     permissionValues:                               
       - handlingunits
    -
     id: product_catalog
     permissionValues:                               
       - Products
    -
     id: integration_hub
     permissionValues:                               
       - IntegrationHUBAPI
    -
     id: reference_management
     permissionValues:                               
       - CoreReferenceManagementService
    -
     id: service_level_management
     permissionValues:                               
       - ServiceLevelsAPI                                
---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb+srv://tcx-dev2:ktV2TuVdFq6wx8d@5nodesnosharding-ty8x3.azure.mongodb.net

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: ${MONGODB_CONNECTION_STRING}