spring:
  application:
    name: navbar-permissions-service
    version: @version@
  profiles:
    active: local
  data:
    mongodb:
      dbname: NavbarPermissionsDB
      database: NavbarPermissionsDB
      uuid-representation: standard

external:
  accountServiceUrl: '#{"${IS_CONTAINER:false}".equals("true") ? "http://tcx-accountappservice" : "https://cloud.dev.api.trimblecloud.com/transportation"}'
  accountServiceEndpoint: /api/core/v2/accounts/
  userServiceUrl: '#{"${IS_CONTAINER:false}".equals("true") ? "http://tcx-iamuserapp" : "https://cloud.dev.api.trimblecloud.com/transportation"}'
  userServiceEndpoint : /iam/v2/users/
  permissionServiceUrl: '#{"${IS_CONTAINER:false}".equals("true") ? "http://tcx-permissionservice" : "https://cloud.dev.api.trimblecloud.com/transportation"}'
  permissionServiceEndpoint : '#{"${IS_CONTAINER:false}".equals("true") ? "/api/v1/role/permissions/" : "/api/v1/manage/roles/permissions/"}'
  authorization:


---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb+srv://tcx-dev2:ktV2TuVdFq6wx8d@5nodesnosharding-ty8x3.azure.mongodb.net

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: ${MONGODB_CONNECTION_STRING}